# Generated by Django 2.2 on 2019-04-17 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=20)),
                ('doc_title', models.CharField(max_length=50)),
                ('deadline_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
