# Generated by Django 2.2 on 2019-04-17 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_snapper_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdata',
            name='deadline_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
